# Generated by Django 4.1.5 on 2023-02-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_address_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='complement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento'),
        ),
    ]
